apiVersion: v1
kind: Service
metadata:
  name: seb-mariadb
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  type: ClusterIP
  selector:
    app: seb-mariadb
